### ISSUE TITLE
Deduplicate simultaneous requests

### ISSUE THREAD

**Issue by cheapsteak** [AlbinoDrought/cachios#44]
Hi

Currently, if multiple axios requests are triggered on the same resource in the same event loop, it will trigger multiple http requests

It would be great if that could be deduplicated

**Comment by AlbinoDrought** [comment]
Confirmed, added a (currently failing) testcase: https://github.com/AlbinoDrought/cachios/commit/5277d1f1c69f0a9dc5296e89746db19548869137

A little funky since I thought this was previously covered and worked, but apparently not.

**Comment by cheapsteak** [comment]
Daaaamn that was quick

**Comment by AlbinoDrought** [comment]
Pushed 2.1.0 that deduplicates these requests: https://www.npmjs.com/package/cachios

:)
