### ISSUE TITLE
Prevent cache for certain routes?

### ISSUE THREAD

**Issue by homerjam** [AlbinoDrought/cachios#5]
I saw this and wondered if it be something you could implement in cachios:

https://gist.github.com/javisperez/4bb09e0437994a659bbcd06f90eeebbf

**Comment by AlbinoDrought** [comment]
When sending requests, you can pass a `ttl` key like so:
```js
const cachios = require('cachios');
cachios.get('http://httpbin.org', {
  ttl: 1000, // persist for 1000 seconds
});
```

If you would like to _not_ cache the request, but still use the `cachios` wrapper, you could do something like this:
```js
const cachios = require('cachios');
cachios.get('http://httpbin.org', {
  ttl: -1, // any ttl below zero will result in no caching https://github.com/mpneuried/nodecache#change-ttl-ttl
});
```

I'm not exactly sure what the linked gist is doing - deleting cached routes after delete requests? Or is it the `cacheable` section?

**Comment by homerjam** [comment]
Ah I see, I hadn't realised that was possible (I guess I assumed TTL was a global setting). That covers my needs. The gist is similar in that it looks for a `__cache` query parameter, so no control of TTL. Deleting the relevant cache on post/delete/put isn't really necessary. Thanks!
