### ISSUE TITLE
Problem using Cachios v2.2.1 with Node 10

### ISSUE THREAD

**Issue by DivneetS** [AlbinoDrought/cachios#50]
I upgraded my node to v10.x and cachios to 2.2.1 and it does not pass my auth tokens to the lower layes of code.

**Comment by AlbinoDrought** [comment]
I can reopen this if a testcase is added, but all current tests pass when running in Node versions 10.x through 15.x: 

- [CI Config](https://github.com/AlbinoDrought/cachios/blob/c609f2b1f7ff67b8a9f55c51209e9a83324d1127/.github/workflows/node.js.yml)
- [Passing Tests](https://github.com/AlbinoDrought/cachios/actions/runs/473676041)
