### ISSUE TITLE
Axios Cancelled Requests

### ISSUE THREAD

**Issue by Vijayasingam** [AlbinoDrought/cachios#55]
Hello,
We recently upgraded to version 2 so that we can get the benefit of caching requests. 
We noticed a minor issue in the library when used along with  axios cancel tokens.

If we cancel a request and fire a new one with the same input parameters, the second request also returns the cancelled promise.

Example: [Run Kit](https://runkit.com/vijayasingam/cachios-axios-cancel-token)

I would be happy to take a look at the code and raise PR, wanted to raise this issue just in case if this is a known issue.

Thank you.

**Comment by AlbinoDrought** [comment]
Fixed about a year later :sweat_smile: Published as 2.2.5
