### ISSUE TITLE
Alternative caching lib

### ISSUE THREAD

**Issue by homerjam** [AlbinoDrought/cachios#6]
Hi there

Would you be interested in a PR allowing for an alternative caching strategy eg. [lru-cache](https://github.com/isaacs/node-lru-cache)?

**Comment by AlbinoDrought** [comment]
Hey,

I'd be alright with a PR for this, but I'd like to avoid any breaking "API" changes as well.

This may already be somewhat possible, especially if the cache is compatible with `node-cache`, which `lru-cache` seems to be. Here's a runkit example: http://runkit.com/albinodrought/cachios-with-custom-cache-strategy

A cleaner way to do this would be appreciated!

**Comment by AlbinoDrought** [comment]
The ability to use alternative caching libraries is now documented outside of this issue and is considered implemented.

Tests have been implemented for this here: https://github.com/AlbinoDrought/cachios/blob/master/tests/customCache.spec.js

Readme section is now available here: https://github.com/AlbinoDrought/cachios#alternative-cache-implementation

Everything said in the previous comment remains true: https://github.com/AlbinoDrought/cachios/issues/6#issuecomment-326717524 (backwards compatible, still requires node-cache)

**Comment by homerjam** [comment]
Awesome! Thanks!
